/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import pl.Kontroler;
import thread.NitSat;
import thread.NitServer;

/**
 *
 * @author Matija1
 */
public class GlavnaServer extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaServer
     */
    public GlavnaServer() {
        setTitle("Server strana");
        initComponents();
        srediFormu();
        sdf = new SimpleDateFormat("H:mm:ss");
    
    }
    private final SimpleDateFormat sdf;
    private NitServer nitServer;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblVreme = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblDatum = new javax.swing.JLabel();
        jbtnPokreniServer = new javax.swing.JButton();
        jbtnPromenaBaze = new javax.swing.JButton();
        jbtnPregledKorisnika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vreme:");

        jLabel2.setText("Datum:");

        jbtnPokreniServer.setText("Pokreni server");
        jbtnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPokreniServerActionPerformed(evt);
            }
        });

        jbtnPromenaBaze.setText("Promena baze");
        jbtnPromenaBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPromenaBazeActionPerformed(evt);
            }
        });

        jbtnPregledKorisnika.setText("Pregled korisnika");
        jbtnPregledKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPregledKorisnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnPokreniServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPromenaBaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnPregledKorisnika)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jlblVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jlblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPromenaBaze)
                    .addComponent(jbtnPregledKorisnika))
                .addGap(8, 8, 8)
                .addComponent(jbtnPokreniServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlblVreme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPokreniServerActionPerformed
//         String brojPorta = jtxtPort.getText().trim();
//        if (brojPorta.isEmpty()) {
           String brojPorta = "9000";
//            jtxtPort.setText("9000");
//        }
//        if (!brojPorta.matches("\\d+")) {
//            JOptionPane.showMessageDialog(this, "Broj porta pogresno unet", "GRESKA", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        try {
            nitServer = new NitServer(brojPorta);
            nitServer.start();
            jbtnPokreniServer.setEnabled(false);
            jbtnPregledKorisnika.setEnabled(true);
//            jbtPromenaBaze.setEnabled(false);
//            jlblBrPorta.setEnabled(false);
//            jtxtPort.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnPokreniServerActionPerformed

    private void jbtnPromenaBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPromenaBazeActionPerformed
        IzmenaBaze ib = new IzmenaBaze(this, true);
        ib.setVisible(true);
    }//GEN-LAST:event_jbtnPromenaBazeActionPerformed

    private void jbtnPregledKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPregledKorisnikaActionPerformed
         PregledKorisnika pk = new PregledKorisnika(this, true);
         pk.setVisible(true);
    }//GEN-LAST:event_jbtnPregledKorisnikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnPokreniServer;
    private javax.swing.JButton jbtnPregledKorisnika;
    private javax.swing.JButton jbtnPromenaBaze;
    private javax.swing.JLabel jlblDatum;
    private javax.swing.JLabel jlblVreme;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        setTitle("Server Gde ima mesta");
        jlblDatum.setText(new SimpleDateFormat("d.M.yyyy.").format(new Date()));
        jbtnPregledKorisnika.setEnabled(false);
        Thread nit = new Thread(new NitSat(jlblVreme));
        nit.start();
        Kontroler.getINSTANCE().staviUMapu("forma", this);
    }
    
//    public void pristigaoZahtev(String zahtev) {
//        jtxtAreaZahtevi.append("<" + sdf.format(new Date()) + "> " + zahtev + "\n");
//    }
}
