package forme;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTextArea;
import pl.Kontroler;
import thread.NitKlijent;

/**
 *
 * @author Matija Veljkovic
 */
public class PregledKorisnika extends javax.swing.JDialog {

    /**
     * Creates new form PregledKorisnika
     */
    public PregledKorisnika(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Pregled korisnika");
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlistKorisnici = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtLogKorisnika = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlistKorisnici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistKorisniciMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlistKorisnici);

        jtxtLogKorisnika.setColumns(20);
        jtxtLogKorisnika.setRows(5);
        jScrollPane2.setViewportView(jtxtLogKorisnika);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlistKorisniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistKorisniciMouseClicked
        int r = jlistKorisnici.getSelectedIndex();
        jtxtLogKorisnika.setText("");
        if (r > -1) {
            jtxtLogKorisnika.setText(onlineKlijenti.get(r).getZahtevi().toString());
        }
    }//GEN-LAST:event_jlistKorisniciMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jlistKorisnici;
    private javax.swing.JTextArea jtxtLogKorisnika;
    // End of variables declaration//GEN-END:variables

    List<NitKlijent> onlineKlijenti;
    
    private void srediFormu() {
        onlineKlijenti = Kontroler.getINSTANCE().getOnlineKlijenti();
        jlistKorisnici.setListData(onlineKlijenti.toArray());
    }
}
